name: build

on:
  push:
  pull_request:
  schedule:
    - cron: '58 23 * * *'

jobs:
  build:
    services:
      postgresql:
        image: postgres:10
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
    strategy:
      fail-fast: true

      matrix:
        ruby_version: [ruby-head]
        rails_version: [edge, '7.1', '7.0', '6.1']
        db: ['sqlite3']

        exclude:
          - ruby_version: 'jruby'
            rails_version: 'edge'

    env:
      RAILS_VERSION: ${{ matrix.rails_version }}
      DB: ${{ matrix.db }}
      POSTGRES_PASSWORD: postgres  # for passing the password to the Rails process
      MYSQL_PASSWORD: root  # for passing the password to the Rails process

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          rubygems: ${{ (matrix.ruby_version < '2.3' && '2.7.11') || (matrix.ruby_version < '2.6' && '3.3.26') || (matrix.ruby_version < '3.0' && '3.4.22') || 'latest' }}
          bundler-cache: true
        continue-on-error: ${{ (matrix.ruby_version == 'ruby-head') || (matrix.ruby_version == 'jruby') || (matrix.rails_version == 'edge') }}
      - run: bundle exec rake test
        continue-on-error: ${{ (matrix.ruby_version == 'ruby-head') || (matrix.ruby_version == 'jruby') || (matrix.rails_version == 'edge') }}
